[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pipapo"
authors = [{ name = "the patricles" }]
license = { text = "MIT" }
description = "pipapo - python implemented particles postprocessor"
dynamic = ["version", "dependencies"]
requires-python = ">=3.10"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = { attr = "pipapo.__version__" }
dependencies = { file = ["requirements.in"] } # No versions fixed
optional-dependencies = { safe = { file = [
    "requirements.txt",
] } } # Every package version is fixed

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = "tests/pipapo_testing_utils"

[project.optional-dependencies]
develop = [
    "black",
    "pytest",
    "pylint",
    "pylint-exit",
    "isort>=5.0",
    "pre-commit",
    "pre-commit-hooks>=4.4.0",
    "commitizen",
    "pydocstyle",
    "docformatter",
    "pytest-cov",
    "mypy",
]

[tool.isort]
profile = "black"

[tool.pylint]
max-args = 10
max-positional-arguments = 10
max-locals = 20

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "R0801",  # duplicate-code
]
